#!/bin/bash

# __is_clean__is_uptodate__is_added__is_changes__is_untracked

test_cmd=git
type ${test_cmd} > /dev/null 2>&1 || { echo -e >&2 "[\033[31m${test_cmd}\033[0m] not installed."; exit 1; }

ret=`git status 2>/dev/null`
ret_r="$?"

__is_clean() {
	echo $ret | grep -q "nothing to commit, working tree clean"
    if [ "$?" == 0 ] ; then
		echo 1
    else
		echo 0
    fi
}

__is_uptodate() {
	echo $ret | grep -q "Your branch is up to date"
    if [ "$?" == 0 ] ; then
        echo 1
    else
        echo 0
    fi
}

__is_added() {
	echo $ret | grep -q "Changes to be committed"
    if [ "$?" == 0 ] ; then
        echo 1
    else
        echo 0
    fi
}

__is_changes() {
	echo $ret | grep -q "Changes not staged for commit"
    if [ "$?" == 0 ] ; then
        echo 1
    else
        echo 0
    fi
}

__is_untracked() {
	echo $ret | grep -q "Untracked files"
    if [ "$?" == 0 ] ; then
        echo 1
    else
        echo 0
    fi
}


if [ "$ret_r" == 0 ] ; then
	echo `__is_clean``__is_uptodate``__is_added``__is_changes``__is_untracked`
else
	# wrong
	echo -1
fi
