#!/bin/bash

IFS=$'\n'

dir_list=`ls -l | grep ^d`

echo " Commit  Push"

for i in ${dir_list[@]} ; do
	cd ${i##*\ }
	tmpResult=`git status 2>/dev/null`

	# 合法git项目目录
	if [ "$?" == 0 ] ; then
		echo $tmpResult | grep -q "nothing to commit, working tree clean"
		if [ $? == 1 ] ; then
			echo -en "[\033[31mCOMMIT\033[0m]"
		else
			echo -en "[\033[32m  OK  \033[0m]"
		fi
		
		echo $tmpResult | grep -q "use \"git push\" to publish your local commits"
		if [ $? == 0 ] ; then
			echo -en "[\033[31mPUSH\033[0m]"
		else
			echo -en "[\033[32m OK \033[0m]"
		fi

		echo " "${i##*\ }
	fi
	cd ..
done
