#!/bin/bash

IFS=$'\n'

dir_list=`ls -l | grep ^d`

test_cmd=ggitStatus
type ${test_cmd} > /dev/null 2>&1 || { echo -e >&2 "[\033[31m${test_cmd}\033[0m] not installed."; exit 1; }

for i in ${dir_list[@]} ; do
	cd ${i##*\ }

	ret=`ggitStatus`

	if [ "$ret" != -1 ] ; then
		if [ "$1" == "--gpoo" ] ; then
			echo -e "\033[34m-------------------------------------------------\033[0m"
			gpoo --pull
		fi

		# is remote
		if [ "${ret:5:1}" == 1 ] ; then
			# is up to date
			if [ "${ret:1:1}" == 1 ] ; then
				echo -en "\033[32m*\033[0m"
			else
				echo -en "\033[31m*\033[0m"
			fi
		fi

		# is clean
		if [ "${ret:0:1}" == 1 ] ; then
			echo -en "(\033[32m"`ggitGetCurrentBranch`"\033[0m)"
		else
			echo -en "(\033[35m"`ggitGetCurrentBranch`"\033[0m "
			# is untracked
			if [ "${ret:4:1}" == 1 ] ; then
				echo -en "\033[31m-\033[0m"
			fi
						
			# is changes
			if [ "${ret:3:1}" == 1 ] ; then
				echo -en "\033[31m*\033[0m"
			fi

			# is added
			if [ "${ret:2:1}" == 1 ] ; then
				echo -en "\033[32m+\033[0m"
			fi
			echo -n ")"
		fi
		echo " "${i##*\ }
	fi
	cd ..
done
