#!/bin/bash

# only macOS
# mac: `date -r 1500000000 "+%y%m%d_%H%M%S"`
# linux: `date -d @1500000000 "+%y%m%d_%H%M%S"`

# Batch Rename Script.
# rename by modify time.
# eg: 170714_104000

mkdir ~/Downloads/_o_ 2>/dev/null
cd ~/Downloads/_o_/
_out_path=`pwd`

cd ~/Downloads/_/
_work_path=`pwd`

IFS=$'\n'

_appendSuffix=$1

_num=0
for cur in $_work_path/*
do
	_num=`expr $_num + 1`
	echo $_num
	# get file suffix
	_suffix=${cur##*.}
    if [ "$_suffix" == "$cur" ] ; then
		_suffix=""
    else
		_suffix="."${_suffix}
    fi

	# get modify time
	_mtime=`stat -s $cur`
	_mtime=${_mtime##*st_mtime=}
	_mtime=${_mtime%%\ *}
	_mtimes=`date -r $_mtime "+%y%m%d_%H%M%S"`

	# if already existed
	while [ -f ${_out_path}/${_mtimes}${_suffix} ] ; do
		_mtime=`expr $_mtime + 1`
		_mtimes=`date -r $_mtime "+%y%m%d_%H%M%S"`
	done

	_filename=${_mtimes}${_appendSuffix}${_suffix}
	mv -i $cur ${_out_path}/${_filename}

	echo $cur
	echo $_filename
done
