#!/bin/bash

# Sequence Rename Script.
# $1: Shortest number length.
# $2: Start number.
# $3: Base NAME.

# work path
mkdir ~/Downloads/_o_/ 2>/dev/null
cd ~/Downloads/_o_/
_out_path=`pwd`

cd ~/Downloads/_/
_work_path=`pwd`
IFS=$'\n'

if [ "$1" == "" -o "$2" == "" -o "$3" == "" ] ; then
	echo 'Sequence Rename Script.'
	echo '$1: Shortest number length.'
	echo '$2: Start number.'
	echo '$3: Base NAME.'
else
	_num=$2
	for cur in $_work_path/*
	do
		# get file suffix
		_suffix=${cur##*.}
		if [ "$_suffix" == "$cur" ] ; then
			_suffix=""
		else
			_suffix="."${_suffix}
		fi

		# produce number length
		while [ ${#_num} -lt "$1" ] ; do
			_num="0"${_num}
		done

		_filename=$3${_num}${_suffix}

		mv -i $cur ${_out_path}/${_filename}

		echo $cur
		echo $_filename
		_num=`expr $_num + 1`
	done
fi
